@extends('ceemes::admin.layout', ['title' => 'Media'])

@section('content')
    <div class="ceemes-page-header">
        <div><span class="ceemes-eyebrow">Assets · {{ $mediaDisk }}</span><h1>Media Library</h1><p>Kelola gambar dan dokumen dalam folder yang kompatibel dengan local storage maupun S3.</p></div>
        <div class="ceemes-header-actions"><button class="ceemes-button ceemes-button-secondary" type="button" data-dialog-open="create-media-folder">+ Folder</button><button class="ceemes-button" type="button" data-dialog-open="upload-media">+ Upload Media</button></div>
    </div>

    @if(session('media_usages'))<div class="ceemes-alert ceemes-alert-danger"><strong>Media masih digunakan pada lokasi berikut:</strong><ul>@foreach(session('media_usages') as $usage)<li>{{ $usage['label'] }} — {{ $usage['field_handle'] }}</li>@endforeach</ul></div>@endif

    <div class="ceemes-media-library-layout">
        <aside class="ceemes-folder-panel">
            <div class="ceemes-folder-heading"><strong>Folders</strong><button type="button" title="Buat folder" data-dialog-open="create-media-folder">+</button></div>
            <a class="{{ request('folder', '') === '' ? 'is-active' : '' }}" href="{{ route('ceemes.admin.media.index', array_filter(['q' => request('q'), 'type' => request('type')])) }}"><span>▧</span> Semua file</a>
            <a class="{{ request('folder') === 'root' ? 'is-active' : '' }}" href="{{ route('ceemes.admin.media.index', array_filter(['folder' => 'root', 'q' => request('q'), 'type' => request('type')])) }}"><span>⌂</span> Tanpa folder</a>
            @foreach($folders as $folder)
                <a class="{{ request('folder') === $folder->uuid ? 'is-active' : '' }}" style="padding-left: {{ 12 + substr_count($folder->path, '/') * 15 }}px" href="{{ route('ceemes.admin.media.index', array_filter(['folder' => $folder->uuid, 'q' => request('q'), 'type' => request('type')])) }}"><span>□</span> {{ $folder->name }}</a>
            @endforeach
        </aside>

        <section class="ceemes-panel ceemes-media-panel">
            <form class="ceemes-toolbar" method="GET">
                @if(request('folder'))<input type="hidden" name="folder" value="{{ request('folder') }}">@endif
                <label class="ceemes-search-box"><span>⌕</span><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari filename, title, atau alt…"></label>
                <select class="ceemes-filter" name="type" aria-label="Filter jenis media"><option value="">Semua jenis</option><option value="image" @selected(request('type') === 'image')>Gambar</option><option value="document" @selected(request('type') === 'document')>Dokumen</option><option value="other" @selected(request('type') === 'other')>Lainnya</option></select>
                <button class="ceemes-button ceemes-button-secondary" type="submit">Terapkan</button>
                @if(request('q') || request('type'))<a class="ceemes-button ceemes-button-ghost" href="{{ route('ceemes.admin.media.index', array_filter(['folder' => request('folder')])) }}">Reset filter</a>@endif
                <span class="ceemes-result-count"><strong>{{ $mediaItems->count() }}</strong> file</span>
            </form>
            @if($activeFolder)
                <div class="ceemes-folder-context"><div><span class="ceemes-eyebrow">Folder</span><strong>{{ $activeFolder->name }}</strong><small>{{ $activeFolder->path }}</small></div><form method="POST" action="{{ route('ceemes.admin.media-folders.destroy', $activeFolder) }}" data-confirm="Hapus folder kosong ini?">@csrf @method('DELETE')<button class="ceemes-button ceemes-button-ghost is-danger" type="submit">Hapus folder</button></form></div>
            @endif
            <div class="ceemes-media-grid">
                @forelse($mediaItems as $media)
                    <article class="ceemes-media-card"><div class="ceemes-media-preview">@if(str_starts_with($media->mime_type, 'image/'))<img src="{{ $media->url() }}" alt="{{ $media->alt }}">@else<span>{{ strtoupper($media->extension) }}</span>@endif</div><div class="ceemes-media-meta"><strong title="{{ $media->original_filename }}">{{ $media->title ?: $media->original_filename }}</strong><small>{{ number_format($media->size / 1024, 1) }} KB · {{ $media->extension }}@if($media->folder) · {{ $media->folder->name }}@endif</small><div class="ceemes-row-actions" style="margin-top:10px;justify-content:flex-start"><button class="ceemes-button ceemes-button-secondary ceemes-button-small" type="button" data-dialog-open="media-{{ $media->uuid }}">Edit</button><form method="POST" action="{{ route('ceemes.admin.media.destroy', $media) }}" data-confirm="Periksa penggunaan lalu hapus media ini?">@csrf @method('DELETE')<button class="ceemes-icon-button is-danger" type="submit">⌫</button></form></div></div></article>
                    <dialog class="ceemes-dialog" id="media-{{ $media->uuid }}"><form method="POST" action="{{ route('ceemes.admin.media.update', $media) }}">@csrf @method('PUT')<div class="ceemes-dialog-header"><div><span class="ceemes-eyebrow">Edit asset</span><h2>{{ $media->original_filename }}</h2></div><button type="button" class="ceemes-dialog-close" data-dialog-close>×</button></div><div class="ceemes-dialog-body"><div class="ceemes-form-grid"><div class="ceemes-field"><label>Title</label><input name="title" value="{{ $media->title }}"></div><div class="ceemes-field"><label>Folder</label><select name="folder_uuid"><option value="">Tanpa folder</option>@foreach($folders as $folder)<option value="{{ $folder->uuid }}" @selected($media->folder_uuid === $folder->uuid)>{{ str_repeat('— ', substr_count($folder->path, '/')) }}{{ $folder->name }}</option>@endforeach</select></div><div class="ceemes-field ceemes-field-wide"><label>Alt text</label><input name="alt" value="{{ $media->alt }}"></div><div class="ceemes-field ceemes-field-wide"><label>Caption</label><textarea name="caption">{{ $media->caption }}</textarea></div></div></div><div class="ceemes-dialog-footer"><button type="button" class="ceemes-button ceemes-button-ghost" data-dialog-close>Batal</button><button class="ceemes-button" type="submit">Simpan</button></div></form></dialog>
                @empty<div class="ceemes-empty" style="grid-column:1/-1"><span>▧</span><h3>Tidak ada Media</h3><p>Upload file baru atau ubah filter yang sedang aktif.</p></div>@endforelse
            </div>
        </section>
    </div>

    <dialog class="ceemes-dialog" id="create-media-folder" @if($errors->hasAny(['name', 'parent_uuid', 'folder'])) data-open-on-error @endif><form method="POST" action="{{ route('ceemes.admin.media-folders.store') }}">@csrf<div class="ceemes-dialog-header"><div><span class="ceemes-eyebrow">Media Library</span><h2>Buat Folder</h2></div><button type="button" class="ceemes-dialog-close" data-dialog-close>×</button></div><div class="ceemes-dialog-body"><div class="ceemes-form-grid"><div class="ceemes-field"><label>Nama folder <em>*</em></label><input name="name" required placeholder="Product Photos"></div><div class="ceemes-field"><label>Folder induk</label><select name="parent_uuid"><option value="">Root</option>@foreach($folders as $folder)<option value="{{ $folder->uuid }}" @selected(request('folder') === $folder->uuid)>{{ str_repeat('— ', substr_count($folder->path, '/')) }}{{ $folder->name }}</option>@endforeach</select></div></div><div class="ceemes-inline-note" style="margin-top:15px">Folder disimpan sebagai prefix storage, sehingga tetap bekerja pada disk local, public, dan S3.</div></div><div class="ceemes-dialog-footer"><button type="button" class="ceemes-button ceemes-button-ghost" data-dialog-close>Batal</button><button class="ceemes-button" type="submit">Buat Folder</button></div></form></dialog>

    <dialog class="ceemes-dialog" id="upload-media" @if($errors->has('file')) data-open-on-error @endif><form method="POST" action="{{ route('ceemes.admin.media.store') }}" enctype="multipart/form-data">@csrf<div class="ceemes-dialog-header"><div><span class="ceemes-eyebrow">New asset</span><h2>Upload Media</h2></div><button type="button" class="ceemes-dialog-close" data-dialog-close>×</button></div><div class="ceemes-dialog-body"><div class="ceemes-upload-zone"><span>⇧</span><strong>Pilih file untuk di-upload</strong><input type="file" name="file" required></div><div class="ceemes-form-grid"><div class="ceemes-field"><label>Folder</label><select name="folder_uuid"><option value="">Tanpa folder</option>@foreach($folders as $folder)<option value="{{ $folder->uuid }}" @selected(request('folder') === $folder->uuid)>{{ str_repeat('— ', substr_count($folder->path, '/')) }}{{ $folder->name }}</option>@endforeach</select></div><div class="ceemes-field"><label>Title</label><input name="title"></div><div class="ceemes-field ceemes-field-wide"><label>Alt text</label><input name="alt"></div></div></div><div class="ceemes-dialog-footer"><button type="button" class="ceemes-button ceemes-button-ghost" data-dialog-close>Batal</button><button class="ceemes-button" type="submit">Upload</button></div></form></dialog>
@endsection
