@extends('ceemes::admin.layout', ['title' => 'Media'])

@section('content')
    <div class="ceemes-page-header"><div><span class="ceemes-eyebrow">Assets</span><h1>Media Library</h1><p>Upload, cari, dan kelola file yang digunakan content.</p></div><button class="ceemes-button" type="button" data-dialog-open="upload-media">＋ Upload Media</button></div>
    @if(session('media_usages'))<div class="ceemes-alert ceemes-alert-danger"><strong>Media masih digunakan pada lokasi berikut:</strong><ul>@foreach(session('media_usages') as $usage)<li>{{ $usage['label'] }} — {{ $usage['field_handle'] }}</li>@endforeach</ul></div>@endif
    <section class="ceemes-panel">
        <form class="ceemes-toolbar" method="GET"><label class="ceemes-search-box"><span>⌕</span><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari filename, title, atau alt…"></label><button class="ceemes-button ceemes-button-secondary" type="submit">Cari</button>@if(request('q'))<a class="ceemes-button ceemes-button-ghost" href="{{ route('ceemes.admin.media.index') }}">Reset</a>@endif<span class="ceemes-result-count"><strong>{{ $mediaItems->count() }}</strong> file</span></form>
        <div class="ceemes-media-grid">
            @forelse($mediaItems as $media)
                <article class="ceemes-media-card"><div class="ceemes-media-preview">@if(str_starts_with($media->mime_type, 'image/'))<img src="{{ $media->url() }}" alt="{{ $media->alt }}">@else<span>{{ strtoupper($media->extension) }}</span>@endif</div><div class="ceemes-media-meta"><strong title="{{ $media->original_filename }}">{{ $media->title ?: $media->original_filename }}</strong><small>{{ number_format($media->size / 1024, 1) }} KB · {{ $media->extension }}</small><div class="ceemes-row-actions" style="margin-top:10px;justify-content:flex-start"><button class="ceemes-button ceemes-button-secondary ceemes-button-small" type="button" data-dialog-open="media-{{ $media->uuid }}">Edit</button><form method="POST" action="{{ route('ceemes.admin.media.destroy', $media) }}" data-confirm="Periksa penggunaan lalu hapus media ini?">@csrf @method('DELETE')<button class="ceemes-icon-button is-danger" type="submit">⌫</button></form></div></div></article>
                <dialog class="ceemes-dialog" id="media-{{ $media->uuid }}"><form method="POST" action="{{ route('ceemes.admin.media.update', $media) }}">@csrf @method('PUT')<div class="ceemes-dialog-header"><div><span class="ceemes-eyebrow">Edit asset</span><h2>{{ $media->original_filename }}</h2></div><button type="button" class="ceemes-dialog-close" data-dialog-close>×</button></div><div class="ceemes-dialog-body"><div class="ceemes-form-grid"><div class="ceemes-field"><label>Title</label><input name="title" value="{{ $media->title }}"></div><div class="ceemes-field"><label>Alt text</label><input name="alt" value="{{ $media->alt }}"></div><div class="ceemes-field ceemes-field-wide"><label>Caption</label><textarea name="caption">{{ $media->caption }}</textarea></div></div></div><div class="ceemes-dialog-footer"><button type="button" class="ceemes-button ceemes-button-ghost" data-dialog-close>Batal</button><button class="ceemes-button" type="submit">Simpan</button></div></form></dialog>
            @empty<div class="ceemes-empty" style="grid-column:1/-1"><span>▧</span><h3>Belum ada Media</h3><p>Upload gambar atau dokumen pertama.</p></div>@endforelse
        </div>
    </section>
    <dialog class="ceemes-dialog" id="upload-media" @if($errors->has('file')) data-open-on-error @endif><form method="POST" action="{{ route('ceemes.admin.media.store') }}" enctype="multipart/form-data">@csrf<div class="ceemes-dialog-header"><div><span class="ceemes-eyebrow">New asset</span><h2>Upload Media</h2></div><button type="button" class="ceemes-dialog-close" data-dialog-close>×</button></div><div class="ceemes-dialog-body"><div class="ceemes-upload-zone"><span>⇧</span><strong>Pilih file untuk di-upload</strong><input type="file" name="file" required></div><div class="ceemes-form-grid"><div class="ceemes-field"><label>Title</label><input name="title"></div><div class="ceemes-field"><label>Alt text</label><input name="alt"></div></div></div><div class="ceemes-dialog-footer"><button type="button" class="ceemes-button ceemes-button-ghost" data-dialog-close>Batal</button><button class="ceemes-button" type="submit">Upload</button></div></form></dialog>
@endsection
